#!/usr/bin/env bash
set -euo pipefail

COLLECTIVEOS_ACCENT="#00a86b"
CIDER_COLLECTIVE_KEY_FINGERPRINT="A0CD6B993438E22634450CDD2A236C3F42A61682"
CIDER_COLLECTIVE_KEY_ID="${CIDER_COLLECTIVE_KEY_FINGERPRINT: -16}"
CIDER_COLLECTIVE_KEY_FILE="/etc/pacman.d/keys/cidercollective.asc"

# Import and trust the Cider Collective repo key so pacman never prompts mid-install.
ensure_cidercollective_key() {
  if pacman-key --list-keys "$CIDER_COLLECTIVE_KEY_FINGERPRINT" >/dev/null 2>&1; then
    return
  fi

  local key_source=""
  local temp_key=""

  if [[ -f "$CIDER_COLLECTIVE_KEY_FILE" ]]; then
    key_source="$CIDER_COLLECTIVE_KEY_FILE"
  else
    temp_key="$(mktemp /tmp/cider-key.XXXXXX)"
    if ! curl -fsSL https://repo.cider.sh/RPM-GPG-KEY -o "$temp_key"; then
      echo "Failed to download the Cider Collective repo key" >&2
      rm -f "$temp_key"
      return 1
    fi

    local downloaded_fingerprint
    if ! downloaded_fingerprint="$(gpg --batch --with-colons --show-keys "$temp_key" | awk -F: '/^fpr:/ {print $10; exit}')" || [[ -z "$downloaded_fingerprint" ]]; then
      echo "Unable to determine fingerprint for downloaded Cider Collective repo key" >&2
      rm -f "$temp_key"
      return 1
    fi

    if [[ "$downloaded_fingerprint" != "$CIDER_COLLECTIVE_KEY_FINGERPRINT" ]]; then
      echo "Downloaded Cider Collective repo key fingerprint mismatch" >&2
      rm -f "$temp_key"
      return 1
    fi

    key_source="$temp_key"
  fi

  if ! pacman-key --add "$key_source"; then
    echo "Failed to import the Cider Collective repo key" >&2
    [[ -n "$temp_key" ]] && rm -f "$temp_key"
    return 1
  fi

  [[ -n "$temp_key" ]] && rm -f "$temp_key"

  if ! pacman-key --lsign-key "$CIDER_COLLECTIVE_KEY_ID"; then
    echo "Failed to locally sign the Cider Collective repo key" >&2
    return 1
  fi
}

use_collectiveos_helpers() {
  export COLLECTIVEOS_PATH="/root/collectiveos"
  export COLLECTIVEOS_INSTALL="/root/collectiveos/install"
  export COLLECTIVEOS_INSTALL_LOG_FILE="/var/log/collectiveos-install.log"
  source /root/collectiveos/install/helpers/all.sh
}

run_configurator() {
  set_shades_of_jade_colors
  ./configurator
  export COLLECTIVEOS_USER="$(jq -r '.users[0].username' user_credentials.json)"
}

install_arch() {
  clear_logo
  gum style --foreground "$COLLECTIVEOS_ACCENT" --padding "1 0 0 $PADDING_LEFT" "Installing CollectiveOS..."
  echo

  touch "$COLLECTIVEOS_INSTALL_LOG_FILE"

  start_log_output

  # Set CURRENT_SCRIPT for the trap to display better when nothing is returned for some reason
  CURRENT_SCRIPT="install_base_system"
  install_base_system > >(sed -u 's/\x1b\[[0-9;]*[a-zA-Z]//g' >>"$COLLECTIVEOS_INSTALL_LOG_FILE") 2>&1
  unset CURRENT_SCRIPT
  stop_log_output
}

install_collectiveos() {
  chroot_bash -lc "sudo pacman -S --noconfirm --needed gum" >/dev/null
  chroot_bash -lc "source /home/$COLLECTIVEOS_USER/.local/share/collectiveos/install.sh || bash"

  # Reboot if requested by installer
  if [[ -f /mnt/var/tmp/collectiveos-install-completed ]]; then
    reboot
  fi
}

# Set the Shades of Jade color scheme for the terminal
set_shades_of_jade_colors() {
  if [[ $(tty) == "/dev/tty"* ]]; then
    # Shades of Jade palette
    echo -en "\e]P000110b" # primary bg
    echo -en "\e]P1b91c1c" # warm red accent
    echo -en "\e]P200a86b" # emerald accent
    echo -en "\e]P3f59e0b" # amber accent
    echo -en "\e]P4114b3b" # deep teal
    echo -en "\e]P59147ff" # violet highlight
    echo -en "\e]P666cba6" # jade glow
    echo -en "\e]P7e6f6f0" # primary text
    echo -en "\e]P8002215" # muted bg
    echo -en "\e]P9ff3370" # bright pink alert
    echo -en "\e]PA40a258" # bright emerald
    echo -en "\e]PBffde8a" # golden highlight
    echo -en "\e]PC005436" # rich green
    echo -en "\e]PDC3FCB8" # mint highlight
    echo -en "\e]PE80d4b5" # aqua accent
    echo -en "\e]PFEAEAEA" # soft white (foreground)

    # Set default foreground and background
    echo -en "\033[0m"
    clear
  fi
}

install_base_system() {
  # Initialize and populate the keyring
  pacman-key --init
  pacman-key --populate archlinux
  pacman-key --populate omarchy
  if ! ensure_cidercollective_key; then
    echo "ERROR: Failed to import and locally sign the Cider Collective repo key" >&2
    return 1
  fi

  # Sync the offline database so pacman can find packages
  pacman -Sy --noconfirm

  # Ensure that no mounts exist from past install attempts
  findmnt -R /mnt >/dev/null && umount -R /mnt

  # Install using files generated by the ./configurator
  # Skip NTP and WKD sync since we're offline (keyring is pre-populated in ISO)
  archinstall \
    --config user_configuration.json \
    --creds user_credentials.json \
    --silent \
    --skip-ntp \
    --skip-wkd

  # After archinstall sets up the base system but before our installer runs,
  # we need to ensure the offline pacman.conf is in place
  cp /etc/pacman.conf /mnt/etc/pacman.conf

  # Mount the offline mirror so it's accessible in the chroot
  mkdir -p /mnt/var/cache/collectiveos/mirror/offline
  mount --bind /var/cache/collectiveos/mirror/offline /mnt/var/cache/collectiveos/mirror/offline

  # Mount the packages dir so it's accessible in the chroot
  mkdir -p /mnt/opt/packages
  mount --bind /opt/packages /mnt/opt/packages

  # No need to ask for sudo during the installation (CollectiveOS installer is responsible for removing it after install)
  mkdir -p /mnt/etc/sudoers.d
  cat >/mnt/etc/sudoers.d/99-collectiveos-installer <<EOF
root ALL=(ALL:ALL) NOPASSWD: ALL
%wheel ALL=(ALL:ALL) NOPASSWD: ALL
$COLLECTIVEOS_USER ALL=(ALL:ALL) NOPASSWD: ALL
EOF
  chmod 440 /mnt/etc/sudoers.d/99-collectiveos-installer

  # Copy the local CollectiveOS repo to the user's home directory
  seed_target_cider_key
  mkdir -p /mnt/home/$COLLECTIVEOS_USER/.local/share/
  cp -r /root/collectiveos /mnt/home/$COLLECTIVEOS_USER/.local/share/

  chown -R 1000:1000 /mnt/home/$COLLECTIVEOS_USER/.local/

  # Ensure all necessary scripts are executable
  find /mnt/home/$COLLECTIVEOS_USER/.local/share/collectiveos -type f -path "*/bin/*" -exec chmod +x {} \;
  chmod +x /mnt/home/$COLLECTIVEOS_USER/.local/share/collectiveos/boot.sh 2>/dev/null || true
  chmod +x /mnt/home/$COLLECTIVEOS_USER/.local/share/collectiveos/default/waybar/indicators/screen-recording.sh 2>/dev/null || true
}

seed_target_cider_key() {
  local target_key_dir="/mnt/etc/pacman.d/keys"
  local target_key_file="$target_key_dir/cidercollective.asc"

  mkdir -p "$target_key_dir"

  if [[ -f "$CIDER_COLLECTIVE_KEY_FILE" ]]; then
    cp "$CIDER_COLLECTIVE_KEY_FILE" "$target_key_file"
  else
    if ! curl -fsSL https://repo.cider.sh/RPM-GPG-KEY -o "$target_key_file"; then
      echo "ERROR: Failed to download Cider Collective key for target system" >&2
      return 1
    fi
  fi

  if ! arch-chroot /mnt pacman-key --add /etc/pacman.d/keys/cidercollective.asc; then
    echo "ERROR: Failed to import the Cider Collective key inside the target system" >&2
    return 1
  fi
  if ! arch-chroot /mnt pacman-key --list-keys "$CIDER_COLLECTIVE_KEY_FINGERPRINT" >/dev/null 2>&1; then
    echo "ERROR: Key import failed in target system" >&2
    return 1
  fi
  if ! arch-chroot /mnt pacman-key --lsign-key "$CIDER_COLLECTIVE_KEY_ID"; then
    echo "ERROR: Failed to locally sign the Cider Collective key in the target system" >&2
    return 1
  fi
}

chroot_bash() {
  HOME=/home/$COLLECTIVEOS_USER \
    arch-chroot -u $COLLECTIVEOS_USER /mnt/ \
    env COLLECTIVEOS_CHROOT_INSTALL=1 \
    COLLECTIVEOS_USER_NAME="$(<user_full_name.txt)" \
    COLLECTIVEOS_USER_EMAIL="$(<user_email_address.txt)" \
    USER="$COLLECTIVEOS_USER" \
    HOME="/home/$COLLECTIVEOS_USER" \
    /bin/bash "$@"
}

if [[ $(tty) == "/dev/tty1" ]]; then
  use_collectiveos_helpers
  run_configurator
  install_arch
  install_collectiveos
fi
